// pages/login.vue
<script setup lang="ts">
import { z } from 'zod'
import { reactive, ref } from 'vue'
import { useAuth } from '@/composables/useAuth'
import { LucideEye, LucideEyeClosed } from 'lucide-vue-next'

import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'

const { login } = useAuth()

const form = reactive({
    email: '',
    password: ''
})

const errors = ref<{ email?: string[]; password?: string[] }>({})
const apiError = ref('')
const loading = ref(false)
const showPassword = ref(false)

const schema = z.object({
    email: z.string().email({ message: 'Digite um e-mail válido' }),
    password: z.string().min(6, { message: 'A senha deve ter no mínimo 6 caracteres' })
})

function validate() {
    const result = schema.safeParse(form)

    if (!result.success) {
        errors.value = result.error.flatten().fieldErrors
        return false
    }

    errors.value = {}
    return true
}

async function onSubmit() {
    apiError.value = ''
    if (!validate()) return

    loading.value = true

    try {
        await login(form.email, form.password)
    } catch (err) {
        apiError.value = 'Usuário ou senha inválidos.'
    } finally {
        loading.value = false
    }
}
</script>

<template>
    <div class="w-full h-screen flex items-center justify-center px-4">
        <Card class="mx-auto max-w-sm w-full">
            <CardHeader>
                <CardTitle class="text-2xl">Login</CardTitle>
                <CardDescription>Entre com seu e-mail para acessar sua conta</CardDescription>
            </CardHeader>
            <CardContent>
                <form class="grid gap-4" @submit.prevent="onSubmit">
                    <div v-if="apiError" class="text-sm text-red-500 text-center -mt-2">
                        {{ apiError }}
                    </div>

                    <div class="grid gap-2">
                        <Label for="email">Email</Label>
                        <Input id="email" type="email" placeholder="seu@email.com" v-model="form.email"
                            :class="{ 'border-red-500': errors.email }" />
                        <p v-if="errors.email" class="text-sm text-red-500">{{ errors.email[0] }}</p>
                    </div>

                    <div class="grid gap-2">
                        <div class="flex items-center">
                            <Label for="password">Senha</Label>
                            <NuxtLink to="/forgot-password" class="ml-auto inline-block text-sm underline">
                                Esqueceu a senha?
                            </NuxtLink>
                        </div>
                        <div class="relative">
                            <Input id="password" :type="showPassword ? 'text' : 'password'" v-model="form.password"
                                :class="{ 'border-red-500': errors.password }" class="pr-10" />
                            <button v-if="form.password" type="button"
                                class="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground"
                                @click="showPassword = !showPassword">
                                <component :is="showPassword ? LucideEyeClosed : LucideEye" class="w-5 h-5" />
                            </button>
                        </div>
                        <p v-if="errors.password" class="text-sm text-red-500">{{ errors.password[0] }}</p>
                    </div>

                    <Button type="submit" class="w-full" :disabled="loading">
                        {{ loading ? 'Entrando...' : 'Entrar' }}
                    </Button>
                </form>

                <div class="mt-4 text-center text-sm">
                    Não tem uma conta?
                    <NuxtLink to="/register" class="underline">Cadastre-se</NuxtLink>
                </div>
            </CardContent>
        </Card>
    </div>
</template>

// src/app/login/page.tsx
'use client';

import { useState } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { FcGoogle } from 'react-icons/fc';
import { FaFacebook, FaEye, FaEyeSlash } from 'react-icons/fa';
import Image from 'next/image';

export default function LoginPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const { login } = useAuth();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError('');
    
    try {
      const success = await login(email, password);
      if (!success) {
        setError('Credenciais inválidas');
      }
    } catch (error) {
      console.error('Erro no login:', error);
      setError('Erro ao fazer login');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex">
      {/* Lado Esquerdo - Imagem */}
      <div className="hidden lg:flex w-[70%] relative bg-gradient-to-br from-purple-600 to-purple-800 overflow-hidden">
        {/* Background image with overlay */}
        <div className="absolute inset-0">
          <Image
            src="https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80"
            alt="Modern city skyline with skyscrapers"
            fill
            className="object-cover"
            priority
          />
          <div className="absolute inset-0 bg-gradient-to-b from-purple-600/80 to-purple-800/80 z-10"></div>
        </div>
        
        <div className="relative z-20 w-full flex flex-col items-center justify-center px-24 text-white">
          <h1 className="text-6xl font-bold mb-8">Bem-vindo(a)</h1>
          <p className="text-xl text-primary-100 text-center max-w-2xl">
            Acesse sua conta para gerenciar seus condomínios e acompanhar todas as informações importantes.
          </p>
        </div>
      </div>

      {/* Lado Direito - Formulário */}
      <div className="flex-1 flex flex-col justify-center py-12 px-8 bg-gray-50">
        <div className="w-full max-w-sm mx-auto space-y-8">
          <div className="text-center">
            <h2 className="text-3xl font-bold text-gray-900">
              Login
            </h2>
            <p className="mt-2 text-sm text-gray-600">
              Entre com suas credenciais para continuar
            </p>
          </div>

          {/* Botões de Login Social */}
          <div className="space-y-3">
            <button
              type="button"
              className="w-full flex items-center justify-center gap-3 px-4 py-3 rounded-xl shadow-sm bg-white hover:bg-gray-50 transition-colors duration-200"
            >
              <FcGoogle size={20} />
              <span className="text-gray-700 text-center">Continuar com Google</span>
            </button>
            <button
              type="button"
              className="w-full flex items-center justify-center gap-3 px-4 py-3 rounded-xl shadow-sm bg-[#1877F2] hover:bg-[#1864D9] text-white transition-colors duration-200"
            >
              <FaFacebook size={20} />
              <span className="text-center">Continuar com Facebook</span>
            </button>
          </div>

          <div className="relative">
            <div className="absolute inset-0 flex items-center">
              <div className="w-full border-t border-gray-200" />
            </div>
            <div className="relative flex justify-center text-sm">
              <span className="px-4 bg-gray-50 text-gray-500">
                ou continue com email
              </span>
            </div>
          </div>

          {error && (
            <div className="rounded-lg bg-red-50 p-4 text-sm text-red-700 border border-red-100">
              {error}
            </div>
          )}

          <form className="space-y-6" onSubmit={handleSubmit}>
            <div className="space-y-5">
              <div>
                <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-1">
                  Email
                </label>
                <input
                  id="email"
                  name="email"
                  type="email"
                  autoComplete="email"
                  required
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="w-full px-4 py-3 rounded-xl border border-gray-300 text-gray-900 focus:ring-1 focus:ring-primary-500/20 focus:border-primary-500 transition-all duration-200"
                  placeholder="seu@email.com"
                />
              </div>

              <div>
                <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-1">
                  Senha
                </label>
                <div className="relative">
                  <input
                    id="password"
                    name="password"
                    type={showPassword ? "text" : "password"}
                    autoComplete="current-password"
                    required
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    className="w-full px-4 py-3 rounded-xl border border-gray-300 text-gray-900 focus:ring-1 focus:ring-primary-500/20 focus:border-primary-500 transition-all duration-200"
                    placeholder="••••••••"
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700 focus:outline-none"
                    aria-label={showPassword ? "Ocultar senha" : "Mostrar senha"}
                  >
                    {showPassword ? <FaEyeSlash size={18} /> : <FaEye size={18} />}
                  </button>
                </div>
              </div>
            </div>

            <div className="flex items-center justify-end">
              <a
                href="/forgot-password"
                className="text-sm text-primary-600 hover:text-primary-500 font-medium"
              >
                Esqueceu a senha?
              </a>
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className="w-full bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white font-medium py-3 px-4 rounded-xl transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed shadow-md flex items-center justify-center"
            >
              {isLoading ? 'Entrando...' : 'Entrar'}
            </button>
          </form>

          <div className="text-center">
            <span className="text-sm text-gray-500">
              Não tem uma conta?{' '}
              <a href="/register" className="font-medium text-primary-600 hover:text-primary-500">
                Criar conta
              </a>
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
